
spring:
  thymeleaf:
    cache: false # 禁用 thymeleaf 模板缓存
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://49.234.19.84:3306/kp?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8 #&useSSL=true
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true

mybatis:
  # config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bingyi.kp.pojo
